### ISSUE TITLE
Missing dependency on arch

### ISSUE THREAD

**Issue by samuelbryant** [nejsan/gcalert#4]
After I installed from AUR and ran it, it gave me a `Dependency was not found! No module named 'oauth2client'`. Installing `python-oauth2client` on pacman fixed the problem. I assume there must be a missing dependency in the build file

**Comment by codehearts** [comment]
Whoops, thanks for bringing this to my attention! Seems like this repo has interest again, I'll try to make time tonight to fix up the pkgbuild and maybe get a pipeline in place to make sure they actually install properly

**Comment by codehearts** [comment]
This should be fixed with the 3.2-6 version of the package. Sorry for the long wait, I was trying to automate my pkgbuild deployments and had a little trouble 😅
